//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
//#define CATCH_CONFIG_RUNNER // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

TEST_CASE("Test for Sample Grade 7", "Grade")
{
    REQUIRE(get_grade(40) == "C");
}

TEST_CASE("Test for Sample Grade 8", "Grade")
{
    REQUIRE(get_grade(39) == "C-");
}

TEST_CASE("Test for Sample Grade 9", "Grade")
{
    REQUIRE(get_grade(32) == "D+");
}
