//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
//#define CATCH_CONFIG_RUNNER // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

TEST_CASE("Test for Sample Grade 4", "Grade")
{
    REQUIRE(get_grade(58) == "B");
}

TEST_CASE("Test for Sample Grade 5", "Grade")
{
    REQUIRE(get_grade(57) == "B-");
}

TEST_CASE("Test for Sample Grade 6", "Grade")
{
    REQUIRE(get_grade(51) == "C+");
}
