//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
//#define CATCH_CONFIG_RUNNER // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

TEST_CASE("Test for Sample 2 - x", "[Px]")
{
    REQUIRE(get_Px(5.5, 0.40578905, 1.13446) == Approx(4.5798833863898));
}

TEST_CASE("Test for Sample 2 - y", "[Py]")
{
    REQUIRE(get_Py(5.5, 0.40578905, 1.13446) == Approx(1.9676731822609));
}

TEST_CASE("Test for Sample 2 - z", "[Pz]")
{
    REQUIRE(get_Pz(5.5, 1.13446) == Approx(2.3244204470968)); 
}
