//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
//#define CATCH_CONFIG_RUNNER // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

TEST_CASE("Test for Sample Grade 10", "Grade")
{
    REQUIRE(get_grade(31) == "D");
}

TEST_CASE("Test for Sample Grade 11", "Grade")
{
    REQUIRE(get_grade(25) == "D-");
}

TEST_CASE("Test for Sample Grade 12", "Grade")
{
    REQUIRE(get_grade(24) == "F");
}
