//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
//#define CATCH_CONFIG_RUNNER // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

TEST_CASE("Test for Sample 3 - x", "[Px]")
{
    REQUIRE(get_Px(9.7, 1.39626, 0.872665) == Approx(1.2903408460632));
}

TEST_CASE("Test for Sample 3 - y", "[Py]")
{
    REQUIRE(get_Py(9.7, 1.39626, 0.872665) == Approx(7.3177410226539)); 
}

TEST_CASE("Test for Sample 3 - z", "[Pz]")
{
    REQUIRE(get_Pz(9.7, 0.872665) == Approx(6.2350370348819));
}
