//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
//#define CATCH_CONFIG_RUNNER // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

TEST_CASE("Test for Sample 4 - x", "[Px]")
{
    REQUIRE(get_Px(3, 0.2181662, 1.202532) == Approx(2.7325165595665)); 
}

TEST_CASE("Test for Sample 4 - y", "[Py]")
{
    REQUIRE(get_Py(3, 0.2181662, 1.202532) == Approx(0.60578446154787));
}

TEST_CASE("Test for Sample 4 - z", "[Pz]")
{
    REQUIRE(get_Pz(3, 1.202532) == Approx(1.0799900174732)); 
}
