//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
//#define CATCH_CONFIG_RUNNER // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

TEST_CASE("Test for Sample Grade 1", "Grade")
{
    REQUIRE(get_grade(80.0) == "A");
}

TEST_CASE("Test for Sample Grade 2", "Grade")
{
    REQUIRE(get_grade(70) == "A-");
}

TEST_CASE("Test for Sample Grade 3", "Grade")
{
    REQUIRE(get_grade(69) == "B+");
}
